[2023-04-28 13:00:21,702: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-04-28 13:00:21,713: INFO/MainProcess] mingle: searching for neighbors
[2023-04-28 13:00:22,745: INFO/MainProcess] mingle: all alone
[2023-04-28 13:00:22,766: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2023-04-28 13:00:22,766: INFO/MainProcess] celery@f029401c0205 ready.
[2023-04-28 13:00:27,022: INFO/MainProcess] Events of group {task} enabled by remote.
[2023-04-28 13:00:41,375: INFO/MainProcess] Task tasks.sample_tasks.create_task[3b1fc0af-3ea2-46b2-9c1b-f117532c55ff] received
[2023-04-28 13:00:51,420: INFO/ForkPoolWorker-1] Task tasks.sample_tasks.create_task[3b1fc0af-3ea2-46b2-9c1b-f117532c55ff] succeeded in 10.030299201999696s: True
